# Generated by Django 4.1.5 on 2023-02-25 11:35

from django.db import migrations
import store.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=tinymce.models.HTMLField(
                validators=[store.models.validate_description]
            ),
        ),
    ]
