# Generated by Django 4.1.5 on 2023-03-08 09:06

import pyuploadcare.dj.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_review_delete_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", pyuploadcare.dj.models.ImageGroupField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="store.images"
            ),
        ),
    ]
