# Generated by Django 4.1.5 on 2023-03-09 12:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_images_remove_product_image_product_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
