# Generated by Django 4.1.5 on 2023-03-09 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admins", "0002_alter_vendor_name"),
        ("store", "0006_alter_images_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ("-id",)},
        ),
        migrations.AddField(
            model_name="review",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="admins.vendor",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="store.product",
            ),
        ),
    ]
